name: Run Kernel Build

on:
  workflow_dispatch:
    inputs:
      variant:
        description: 'Kernel Variant (e.g., Normal, Pocket)'
        required: false
        default: 'Normal'

jobs:
  build-gki:
    uses: ./.github/workflows/build.yml
    with:
      version: 'android14-6.1'
      android_version: 'android14'
      kernel_version: '6.1'
      sublevel: '75'
      os_patch_level: '2024-08'
      feature_set: 'FULL'
      variant: ${{ inputs.variant }}
      ksu_branch: 'main'
      susfs_commit: 'gki-android14-6.1'
      build_bypass: true
    secrets: inherit
