name: Run Kernel Build

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  trigger-build:
    uses: ./.github/workflows/build.yml
    with:
      version: 'android14-6.1'
      android_version: 'android14'
      kernel_version: '6.1'
      sublevel: '75'
      os_patch_level: '2024-08'
      feature_set: 'FULL'
      variant: 'Normal'
    secrets: inherit
